name: Discord Bot 7/24

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

concurrency:
  group: discord-bot
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Modülleri Yükle
        run: npm install

      - name: Botu Başlat
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node index.js
